version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: jaegis-nexus-api:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # volumes:
    #   - ./data:/app/data
    #   - ./.env:/app/.env:ro

